# A Travis CI configuration file.

sudo: required

language: scala
scala:
   - 2.11.8

services:
  - docker

notifications:
  email: false
  slack:
    rooms:
      - secure: "Rrj5ya7JV7bfgW3GXZpuRsX2e9/qsTpLLVZAzgq2Z3xW/IVAqeAM8DDR0tjPbR7Nou0RpPtE/ynkps4Qd6CGTBiCULpcGi2cXJ+p35WvaweWlFIKU0Vam9iEWXQ+bG1LwB61LrSmD7DJvOxkZiwtagqUfYLhVeD1WfgcWc/lj0F0julCScujqqJbj/jUnlkSm6VJz9m11NQkvZZ+YFgNYCPAQRmSh59K0ELximJ54C4/af05YHq6QLWUh/2Eoa68p3XzQyONtteMRvbAJgmMGIijQsKa+ZELrZPjz/5EplMA+FEUjoW6tn3NQjQgZOdDHq3fEbnuit0OOBMRu5QhYT0MjV6QJANYmJU2QqVoDubgTtQSeHJNYoM1fI15yfuSCJg+H6FnI0ncXRB3zz7EZ3zksKKeWZ20NQVKBNCYRNIBC8Im3ff8TbZdulH/Qk/NEeOJwpgm8yfUqUqLu3dt13KT0JdxEcQeOX5lRmz+XBrN6C52/fX0NstO2OCxpKhKcq2+B/Y3mCn6ywqAiTtaLyhPrW08cCB3sBX8y5/Q3do8KPWO1MiBc/K+qtK481bnkh41DaLasqpltpEkFhCW/Udl8iuYEkMWZwNdhEUv6uuPiKF9da4FJkhIV3xVYOzrjF6xR2BtmHVGnCVMMoCUQo9tG8K9tOf+omH+KezZPuw="
      - secure: "WgdL9/Z/9+rl6edh+mqDiO0mx8JpxYwIrudYwuZUZ7d/9oUzS8Miid7au7Y1PP0CVPVDEvastw6+NnIVA/BIHTBNj488dTeNXumaaNQlaTTvaI9OLN1w3+GVVFuF64gmJ6I2T6x+qxqlYOwQhyZ8jZEJUXQ3VwE6DPz+KNqpBy+6GgWEvi+2lgGhc2Ko3SPAtcDWAdE6t8ELaO2uLh/JU60ndAi4yT297fOfwWi4I1aee5a+LajbJN6Mz89o5o0Y2GHV83a3D/ablt1CH3kRSErqLV3HDbt5eRR4yFhTPpbZG8yeWcZkP0oKyt3QqSen1paiEeqr7R9OspDf2OLSlWx7TGm/BnNW/3YRI3+gUPHqaJPCLldNRWnbYYd0RFGjVOfVOoYhAWAMdkWT48jX3YGE1LaZ0SwlxpMy5Fpj8Q22SVXY51o5Pw1UomUhGz2Hjfj8b0WbkWQ+q5qpgR8/z4Zfz5i3MY03mQNzeXs4Z9NoznIiz+9eQVpi4tkjUH3o2AFi6VXTdire61vfhFG3iYYqo2woKwNWOVaK/g0l13EVWiK62YxQEUZJbmhLb6VQrABrB2FCWl/+zZOOR3OUeie3AgAmxEwjxN9Y1IgMy0bJWEZ+ECf//39XMgj5Ys/gPsejDjPsWxhO6cuNtGq9K6RsPij1a0E+01JcyrNyNX0="
    on_pull_requests: false
    on_success: change
    on_failure: always
  webhooks:
    urls:
      secure: "WSg7mxT+VzZ/a7wUp9iW+AzRSdUfw4O//PM29lU2Hk7ULmp5kFfKfYIXB2t0l66Wq3XUkTFfwPPQ5fTOYx7c3m3jVquY4LkFCfvDtNCwRPvxhyGSOuz9ywUeY9LlU+k26ZzBagH4WDTju3k03bCq1n2hd86OYKaF3H6M+9YKcSZznxgEMwg9fDjEdK6HXUc8T3SAW1BTMsOY15Y1OuwpRcAzojdEacRTPhbzM/Z0jYXjtgHYb/Jcb7v4vZqBvKZiH3Y4f2pZEdo8Ao56QYMkwTagsajaWfiYdrITj/MAVP8tdaAnkxXB+ZZxU6NSbSF9NsXl9BJE0m48bdtAltnwP3ANpKCxrllFa8GaqM4E8SGR3wFrXBS7K87u30YpNJQmQGEXl/hv8DiduYU+8yDMTxF/rbAprrs+vUVK1cQYMiH14sM1IITkAOviFqKZ99zHkHGetEhIpr51rMXuZ4To6IgXW7MuLm4lJSnTLH4GyELxWb0aK3s9cVRUNLR9KKZ42PnJ+R7JAEBYE9kPyeALR19VKjw1s13axGYk50acsmnOEnrZlgYvHG3pfsGrJ0OJhbK/G7JlVST7whJAs+oYj1nX79EPGeXbdpx0AFpShfE+xHlsOZ5ANq1h8gksE1D8cdc7XSNC2rvW+iANsG6GhNw5I3EOPGT+9SCg1HAlPdc="

before_install:
  - pip install --upgrade pip setuptools six
  - pip3 install --upgrade pip setuptools six
  - ./tools/travis/flake8.sh  # Check Python files for style and stop the build on syntax errors

install:
  - ./tools/travis/setup.sh

script:
  - ./tools/travis/build.sh
  - ansible-playbook -i ansible/environments/local ansible/logs.yml # collect logs regardless of build exit
  - ./tools/travis/box-upload.py "$TRAVIS_BUILD_DIR/logs" "$TRAVIS_BUILD_ID-$TRAVIS_BRANCH.tar.gz"
