---
# Tasks for handling SDK generation and publishing

- name: ensure nginx config directory exists
  file:
    path: "{{ nginx.confdir }}"
    state: directory
  become: sdk.dir.become

# Blackbox

- name: make temp dir
  local_action: shell "mktemp" "-d" "{{ lookup('env', 'TMPDIR') | default('/tmp', true) }}/whisk.XXXXXXXX"
  register: tmpdir

- name: copy docker sdk to dockerSkeleton in scratch space
  local_action: copy src="{{ openwhisk_home }}/sdk/docker/{{ item }}" dest="{{ tmpdir.stdout }}/dockerSkeleton/"
  with_items:
    - buildAndPush.sh
    - Dockerfile
    - example.c
    - README.md

- name: rename base image in Dockerfile
  local_action: replace dest="{{ tmpdir.stdout }}/dockerSkeleton/Dockerfile" regexp='^FROM dockerskeleton*.*$' replace='FROM openwhisk/dockerskeleton'

- name: fix file permissions
  local_action: file path="{{ tmpdir.stdout }}/dockerSkeleton/buildAndPush.sh" mode=0755

- name: build blackbox container artifact
  local_action: shell "tar" "--exclude=build.gradle" "-czf" "{{ tmpdir.stdout }}/blackbox-0.1.0.tar.gz" "dockerSkeleton" chdir="{{ tmpdir.stdout }}"

- name: copy blackbox container artifact to nginx
  copy:
    src: "{{ tmpdir.stdout }}/blackbox-0.1.0.tar.gz"
    dest: "{{ nginx.confdir }}"

- name: remove temp dir
  local_action: file path="{{ tmpdir.stdout }}" state=absent
