---
# This role will run a CouchDB server on the db group

- name: check if db credentials are valid for CouchDB
  fail: msg="The db provider in your {{ inventory_dir }}/group_vars/all is {{ db_provider }}, it has to be CouchDB, pls double check"
  when: db_provider != "CouchDB"

- name: check for persistent disk
  shell: df -h
  register: disk_status
  when: block_device is defined

- name: "set the volume_dir"
  vars:
    instance: "{{instances | selectattr('name', 'equalto', 'db') | list | first}}"
  set_fact:
    volume_dir: "{{ instance.volume.fsmount | default( '/mnt/' + group_names|first, true ) }}:/usr/local/var/lib/couchdb"
  when: (block_device is defined) and (block_device in disk_status.stdout)

- name: "pull the couchdb:{{ couchdb.version }} image"
  shell: "docker pull couchdb:{{ couchdb.version }}"
  retries: "{{ docker.pull.retries }}"
  delay: "{{ docker.pull.delay }}"

- name: (re)start CouchDB
  docker_container:
    name: couchdb
    image: couchdb:{{ couchdb.version }}
    state: started
    recreate: true
    restart_policy: "{{ docker.restart.policy }}"
    volumes: "{{volume_dir | default([])}}"
    ports:
      - "{{ db_port }}:5984"

- name: wait until the CouchDB in this host is up and running
  wait_for:
    delay: 2
    host: "{{ ansible_host }}"
    port: "{{ db_port }}"
    timeout: 60

- name: create admin user
  uri:
    url: "{{ db_protocol }}://{{ ansible_host }}:{{ db_port }}/_config/admins/{{ db_username }}"
    method: PUT
    body: >
        "{{ db_password }}"
    body_format: json
    status_code: 200

- name: disable reduce limit on views
  uri:
    url: "{{ db_protocol }}://{{ ansible_host }}:{{ db_port }}/_config/query_server_config/reduce_limit"
    method: PUT
    body: >
        "false"
    body_format: json
    status_code: 200
    user: "{{ db_username }}"
    password: "{{ db_password }}"
    force_basic_auth: yes
