---
# This role will run a CouchDB server on the db group

- name: "Set node name to couchdb{{ groups['db'].index(inventory_hostname) }}"
  set_fact:
    nodeName: "couchdb{{ groups['db'].index(inventory_hostname) }}"

- name: check if db credentials are valid for CouchDB
  fail: msg="The db provider in your {{ inventory_dir }}/group_vars/all is {{ db_provider }}, it has to be CouchDB, pls double check"
  when: db_provider != "CouchDB"

- name: check for persistent disk
  shell: df -h
  register: disk_status
  when: block_device is defined

- name: "set the volume_dir"
  vars:
    instance: "{{instances | selectattr('name', 'equalto', 'db') | list | first}}"
  set_fact:
    volume_dir: "{{ instance.volume.fsmount | default( '/mnt/' + group_names|first, true ) }}:/usr/local/var/lib/couchdb"
  when: (block_device is defined) and (block_device in disk_status.stdout)

- name: "pull the klaemo/couchdb:{{ couchdb.version }} image"
  shell: "docker pull klaemo/couchdb:{{ couchdb.version }}"
  retries: "{{ docker.pull.retries }}"
  delay: "{{ docker.pull.delay }}"

- name: (re)start CouchDB
  docker_container:
    name: couchdb
    image: klaemo/couchdb:{{ couchdb.version }}
    state: started
    recreate: true
    restart_policy: "{{ docker.restart.policy }}"
    volumes: "{{volume_dir | default([])}}"
    ports:
      - "{{ db_port }}:5984"
    env:
      COUCHDB_USER: "{{ db_username }}"
      COUCHDB_PASSWORD: "{{ db_password }}"
      NODENAME: "{{ nodeName }}"

- name: wait until CouchDB in this host is up and running
  uri:
    url: "{{ db_protocol }}://{{ ansible_host }}:{{ db_port }}/_utils/"
  register: result
  until: result.status == 200
  retries: 12
  delay: 5

- name: disable reduce limit on views
  uri:
    url: "{{ db_protocol }}://{{ ansible_host }}:{{ db_port }}/_node/couchdb@{{ nodeName }}/_config/query_server_config/reduce_limit"
    method: PUT
    body: >
        "false"
    body_format: json
    status_code: 200
    user: "{{ db_username }}"
    password: "{{ db_password }}"
    force_basic_auth: yes
