---

# Download the cli for the remote mode and generate the content.json file

- name: "download the binaries from the release page of OpenWhisk CLI"
  include: download_openwhisk_cli.yml
  with_items:
    - "{{ cli_os_arch }}"

- name: "generate content.json locally for Nginx CLI directory"
  local_action: shell "./createContentJson.sh" "{{ config_root_dir }}" "{{ openwhisk_cli_tag }}" "{{ cli_os_arch | sort | map('join', ',') | join(' ') }}" "{{ openwhisk_cli.remote.dest_name }}" chdir="{{ openwhisk_home }}/ansible/roles/cli/files"

- name: "ensure Nginx cli directory is writable"
  file:
    path: "{{ cli.nginxdir }}"
    state: directory
    mode: 0777
  become: "{{ cli.dir.become }}"

- name: "copy the local content.json to the remote node"
  copy: src={{ config_root_dir }}/content.json dest={{ cli.nginxdir }}/

- name: "delete the local content.json"
  local_action: file path={{ config_root_dir }}/content.json state=absent
