---
# Install the API Gateway route management actions.

- include: db.yml

- name: install route management actions
  shell: ./installRouteMgmt.sh {{ catalog_auth_key }} {{ groups['edge'] | first }} {{ catalog_namespace }} {{ cli_path }} chdir="{{ openwhisk_home }}/ansible/roles/routemgmt/files"
  environment:
    OPENWHISK_HOME: "{{ openwhisk_home }}"
