---
# This role will install apigateway

- name: "determine the docker_image to use for apigatewy"
  set_fact:
    apigateway_image: "{{ apigateway.docker_image | default('openwhisk/apigateway:' ~ apigateway.version) }}"

- name: "pull the {{ apigateway_image }} docker image"
  shell: "docker pull {{ apigateway_image }}"
  when: apigateway_local_build is undefined
  retries: "{{ docker.pull.retries }}"
  delay: "{{ docker.pull.delay }}"

- name: (re)start apigateway
  docker_container:
    name: apigateway
    image: "{{ apigateway_image }}"
    state: started
    recreate: true
    restart_policy: "{{ docker.restart.policy }}"
    hostname: apigateway
    env:
      "REDIS_HOST": "{{ groups['redis'] | first }}"
      "REDIS_PORT": "{{ redis.port }}"
      "PUBLIC_MANAGEDURL_HOST": "{{ ansible_host }}"
      "PUBLIC_MANAGEDURL_PORT": "{{ apigateway.port.mgmt }}"
    ports:
      - "{{ apigateway.port.mgmt }}:8080"
      - "{{ apigateway.port.api }}:9000"

- name: wait until the API Gateway in this host is up and running
  uri:
    url: "http://{{ groups['apigateway'] | first }}:{{ apigateway.port.api }}/v1/apis"
  register: result
  until: result.status == 200
  retries: 12
  delay: 5
