---
# This task will initialize the immortal DBs in the database account.
# This step is usually done only once per deployment.

- include: db/recreateDb.yml
  vars:
    dbName: "{{ db.whisk.auth }}"
    forceRecreation: False

- include: db/recreateDoc.yml
  vars:
    dbName: "{{ db.whisk.auth }}"
    doc: "{{ lookup('file', '{{ item }}') }}"
  with_items:
    - "{{ openwhisk_home }}/ansible/files/auth_index.json"
    - "{{ openwhisk_home }}/ansible/files/filter_design_document.json"

- name: create necessary "auth" keys
  include: db/recreateDoc.yml
  vars:
    key: "{{ lookup('file', 'files/auth.{{ item }}') }}"
    dbName: "{{ db.whisk.auth }}"
    doc: >
      {
        "_id": "{{ item }}",
        "subject": "{{ item }}",
        "uuid": "{{ key.split(":")[0] }}",
        "key": "{{ key.split(":")[1] }}",
        "namespaces": []
      }
  with_items: "{{ db.authkeys }}"
