---
# Remove nginx containers.

- name: remove nginx
  docker_container:
    name: nginx
    image: nginx
    state: absent
  ignore_errors: True

- name: remove nginx config directory
  file:
    path: "{{ nginx.confdir }}"
    state: absent
  become: nginx.dir.become

- name: remove nginx log directory
  file:
    path: "{{ whisk_logs_dir }}/nginx"
    state: absent
  become: logs.dir.become
