---
# This role starts a nginx component

- name: ensure nginx config directory exists
  file:
    path: "{{ nginx_conf_dir }}"
    state: directory

- name: copy template from local to remote in nginx config directory
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_dir }}/nginx.conf"

- name: copy cert files from local to remote in nginx config directory
  copy:
    src: "files/{{ item }}"
    dest: "{{ nginx_conf_dir }}"
  with_items:
        - "{{ nginx.ssl.cert }}"
        - "{{ nginx.ssl.key }}"

- name: copy password files for cert from local to remote in nginx config directory
  copy:
    src: "files/{{ nginx.ssl.password_file }}"
    dest: "{{ nginx_conf_dir }}"
  when: nginx.ssl.password_enabled == true

- name: ensure nginx log directory is created with permissions
  file:
    path: "{{ whisk_logs_dir }}/nginx"
    state: directory
    mode: 0777
  become: true

- name: "pull the nginx:{{ nginx.version }} image"
  shell: "docker pull nginx:{{ nginx.version }}"

- name: (re)start nginx
  docker_container:
    name: nginx
    image: nginx:{{ nginx.version }}
    state: started
    recreate: true
    restart_policy: "{{ docker.restart.policy }}"
    hostname: "nginx"
    volumes:
      - "{{ whisk_logs_dir }}/nginx:/logs"
      - "{{ nginx_conf_dir }}:/etc/nginx"
    expose:
      - 8443
    ports:
      - "{{ nginx.port.http }}:80"
      - "{{ nginx.port.api }}:443"
      - "{{ nginx.port.adminportal }}:8443"
