apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.namespace}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ow-router-sa
  namespace: {{.Values.namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: knative-serving
  name: ow-router-knative-serving-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: knative-serving
  name: ow-router-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ow-router-knative-serving-role
subjects:
  - kind: ServiceAccount
    name: ow-router-sa
    namespace: {{.Values.namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: {{.Values.namespace}}
  name: ow-router-manage-services-role
rules:
  - apiGroups: ["serving.knative.dev"]
    resources: ["services"]
    verbs: ["create", "list", "watch", "get", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: {{.Values.namespace}}
  name: ow-router-kn-manage-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ow-router-manage-services-role
subjects:
  - kind: ServiceAccount
    name: ow-router-sa
    namespace: {{.Values.namespace}}
---
apiVersion: v1
kind: Secret
metadata:
  name: acr-auth
  namespace: {{.Values.namespace}}
data:
  .dockerconfigjson:  {{ template "imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: ow-router-service
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: ow-router
  ports:
    - protocol: TCP
      name: http-api-server
      port: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ow-router-deployment
  namespace: {{.Values.namespace}}
  labels:
    app: ow-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ow-router
  template:
    metadata:
      labels:
        app: ow-router
    spec:
      serviceAccountName: ow-router-sa
      containers:
        - name: ow-router
          image: {{.Values.imageCredentials.registry}}/ow-knative/ow-router:{{.Values.router.image.tag}}
          args: ["--etcd", "http://router-etcd.default.svc.cluster.local:2379", "--namespace", "{{.Values.namespace}}", "--production"]
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
      {{ if .Values.router.registry_cred }}
      imagePullSecrets:
        - name: {{.Values.router.registry_cred}}
      {{end}}

